### ISSUE TITLE
luci-in-docker编译不进lean？还是说需要特别安装

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-in-docker#1]

**Comment by lisaac** [comment]
这个项目并非 openwrt 的插件，而是 docker 镜像
作用是将 luci 运行在 docker 中，README 中有说明

**Comment by tcsr200722** [comment]
目前直接编译dockerman进op，里面是没有docker镜像文件的，能否把docker直接封装进去


 
---原始邮件---
发件人: "lisaac"<notifications@github.com&gt;
发送时间: 2020年1月4日 07:41:08
收件人: "lisaac/luci-in-docker"<luci-in-docker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [lisaac/luci-in-docker] luci-in-docker编译不进lean？还是说需要特别安装 (#1)



这个项目并非 openwrt 的插件，而是 docker 镜像
 作用是将 luci 运行在 docker 中，README 中有说明

**Comment by lisaac** [comment]
不是很明白你的意思
lean's lede 已经 buildin docker ce 了，打开相关选项即可

另外如果你需要镜像的话，自行从 docker hub 拉取，或者 build ，这个属于 docker 使用范围，与插件无关

**Comment by tcsr200722** [comment]
lean's lede编译后并未内置dockerce,我的意思就是能否内置dockerce

**Comment by lisaac** [comment]
编译的时候手动选择 docker ce 即可
我并不希望添加 docker ce 为依赖

**Comment by tcsr200722** [comment]
里面只有一个luci_app-docker，并不能手动选择ce


 
---原始邮件---
发件人: "lisaac"<notifications@github.com&gt;
发送时间: 2020年1月4日 18:20:25
收件人: "lisaac/luci-in-docker"<luci-in-docker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [lisaac/luci-in-docker] luci-in-docker编译不进lean？还是说需要特别安装 (#1)



编译的时候手动选择 docker ce 即可
 我并不希望添加 docker ce 为依赖

**Comment by lisaac** [comment]
选他即可
另外 docker-ce 应该在 util 中寻找
