### ISSUE TITLE
咨询这个项目的使用方法

### ISSUE THREAD

**Issue by ywgf88** [lisaac/luci-in-docker#3]
大佬:
1.该镜像是否可以直接在openwrt下直接用docker拉取？我看镜像里要求外置硬盘？如果没有外置硬盘是不是就没法玩？拉取后是不是在openwrt里有一项是专门的docker菜单？

2.该镜像如使用latest，会自动部署dockerman和diskman，那么我是否可以理解为不需要在大雕固件里编译你的dockerman和diskman，直接使用该项目就可以了？

3我是否可以在第三方linux下使用该镜像？如debian或者nas的OMV？

**Comment by ywgf88** [comment]
/external:rslave  中的rslave是设备还是目录？如果是设备，我怎么去定制这个设备呢？直接挂载在/external下？

**Comment by lisaac** [comment]
1.可以在 `openwrt` 中拉取，你部署的时候，需要避开 80 端口，理论上只要有 `docker` 环境，都可以部署。
  `external` 并非指的外置硬盘，而是对于 `luci 容器` 来讲的，具体作用可以看 README 关于目录结构部分。

2.可以

3.可以

- `rslave` 是挂载标志，和设备无关

**Comment by ywgf88** [comment]
谢谢你的答复

**Comment by lisaac** [comment]
噢，对了，由于存在二进制文件，目前只支持 x86 构建

**Comment by ywgf88** [comment]
如你所说，我用H96 max X3的盒子编译的openwrt，由于是arm，拉取镜像的时候报错。

我用x86_64来编译，直接在编译里openwert加入dockerman的源，已经成功编译进去了：
git clone https://github.com/lisaac/luci-in-docker.git package/luci-in-docker
git clone https://github.com/lisaac/luci-app-dockerman.git package/luci-app-dockerman

再次感谢！！！
