### ISSUE TITLE
大佬 在vps上安装后出现打开容器和镜像错误

### ISSUE THREAD

**Issue by kissyouhunter** [lisaac/luci-in-docker#4]
VPS ubuntu 18.04.5
打开容器的时候显示如下
Failed to execute cbi dispatcher target for entry '/admin/docker/containers'.
The called action terminated with an exception:
/tmp/.luci/usr/lib/lua/nixio/fs.lua:25: bad argument #1 to 'open' (string expected, got nil)
stack traceback:
	[C]: in function 'open'
	/tmp/.luci/usr/lib/lua/nixio/fs.lua:25: in function </tmp/.luci/usr/lib/lua/nixio/fs.lua:24>
	(tail call): ?
	.../usr/lib/lua/luci/model/cbi/dockerman/containers.lua:110: in function 'func'
	/tmp/.luci/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/tmp/.luci/usr/lib/lua/luci/dispatcher.lua:1002: in function </tmp/.luci/usr/lib/lua/luci/dispatcher.lua:997>
打开竟像时
Failed to execute cbi dispatcher target for entry '/admin/docker/images'.
The called action terminated with an exception:
/tmp/.luci/usr/lib/lua/nixio/fs.lua:25: bad argument #1 to 'open' (string expected, got nil)
stack traceback:
	[C]: in function 'open'
	/tmp/.luci/usr/lib/lua/nixio/fs.lua:25: in function </tmp/.luci/usr/lib/lua/nixio/fs.lua:24>
	(tail call): ?
	...luci/usr/lib/lua/luci/model/cbi/dockerman/images.lua:146: in function 'func'
	/tmp/.luci/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/tmp/.luci/usr/lib/lua/luci/dispatcher.lua:1002: in function </tmp/.luci/usr/lib/lua/luci/dispatcher.lua:997>

**Comment by lisaac** [comment]
什么环境？
容器的运行命令贴下

**Comment by lisaac** [comment]
由于配置文件更换导致的问题，晚上修

**Comment by lisaac** [comment]
已修复，请重新拉取镜像
