### ISSUE TITLE
大佬 方便的话能编译个支持arm64的镜像吗

### ISSUE THREAD

**Issue by kissyouhunter** [lisaac/luci-in-docker#5]
想部署在arm架构的vps上
把portainer替换掉

**Comment by lisaac** [comment]
已加入，没设备，请自行测试

**Comment by kissyouhunter** [comment]
> 已加入，没设备，请自行测试

勤苦
我来测试
有问题再来反馈

**Comment by kissyouhunter** [comment]
大佬好像支持的平台有问题
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
![image](https://user-images.githubusercontent.com/63334206/124159045-3e1a6480-dacd-11eb-94ee-a45b1341f1d7.png)

ARCH 里面显示的还是amd64

**Comment by lisaac** [comment]
有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试

**Comment by kissyouhunter** [comment]
> 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试

好嘞

**Comment by kissyouhunter** [comment]
> 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试

好嘞

**Comment by lisaac** [comment]
> > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> 
> 好嘞

测试结果麻烦发一下噢

**Comment by kissyouhunter** [comment]
> > > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> > 
> > 
> > 好嘞
> 
> 测试结果麻烦发一下噢

大佬还是同样的问题
![image](https://user-images.githubusercontent.com/63334206/124254121-53d66b00-db5b-11eb-87be-c7fb821f2d9f.png)

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
和platform 不match

**Comment by lisaac** [comment]
> > > > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> 
> > > 
> 
> > > 
> 
> > > 好嘞
> 
> > 
> 
> > 测试结果麻烦发一下噢
> 
> 
> 
> 大佬还是同样的问题
> 
> ![image](https://user-images.githubusercontent.com/63334206/124254121-53d66b00-db5b-11eb-87be-c7fb821f2d9f.png)
> 
> 
> 
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 
> 和platform 不match

只是下载吗，有没有试着跑过？

**Comment by kissyouhunter** [comment]
> > > > > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 好嘞
> > 
> > 
> > > 
> > 
> > 
> > > 测试结果麻烦发一下噢
> > 
> > 
> > 大佬还是同样的问题
> > ![image](https://user-images.githubusercontent.com/63334206/124254121-53d66b00-db5b-11eb-87be-c7fb821f2d9f.png)
> > WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> > 和platform 不match
> 
> 只是下载吗，有没有试着跑过？

刚重新装了一下
log显示正常了
目前没啥问题
用dockerman把portainer的容器和镜像都删除了
这是在建立容器的时候有这个warning
不影响正常使用
我看了下docekr hub ARCH 下面还是显示的amd64

**Comment by lisaac** [comment]
> > > > > > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 好嘞
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 测试结果麻烦发一下噢
> 
> > > 
> 
> > > 
> 
> > > 大佬还是同样的问题
> 
> > > ![image](https://user-images.githubusercontent.com/63334206/124254121-53d66b00-db5b-11eb-87be-c7fb821f2d9f.png)
> 
> > > WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 
> > > 和platform 不match
> 
> > 
> 
> > 只是下载吗，有没有试着跑过？
> 
> 
> 
> 刚重新装了一下
> 
> log显示正常了
> 
> 目前没啥问题
> 
> 用doclerman把portainer的容器和镜像都删除了
> 
> 这是在建立容器的时候有这个warning
> 
> 不影响正常使用
> 
> 我看了下docekr hub ARCH 下面还是显示的amd64

嗯，用docker hub ci自动编译没有选项修改manifest
可能需要hooks build自己修改build命令，既然不影响使用就等空了再加

**Comment by kissyouhunter** [comment]
> > > > > > > 有个typo错误已经修复，dockerhub编译中，过半小时后再pull试试
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 好嘞
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 测试结果麻烦发一下噢
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 大佬还是同样的问题
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/63334206/124254121-53d66b00-db5b-11eb-87be-c7fb821f2d9f.png)
> > 
> > 
> > > > WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> > 
> > 
> > > > 和platform 不match
> > 
> > 
> > > 
> > 
> > 
> > > 只是下载吗，有没有试着跑过？
> > 
> > 
> > 刚重新装了一下
> > log显示正常了
> > 目前没啥问题
> > 用doclerman把portainer的容器和镜像都删除了
> > 这是在建立容器的时候有这个warning
> > 不影响正常使用
> > 我看了下docekr hub ARCH 下面还是显示的amd64
> 
> 嗯，用docker hub ci自动编译没有选项修改manifest
> 可能需要hooks build自己修改build命令，既然不影响使用就等空了再加

好嘞
大佬辛苦
